spring:
  application:
    name: "bank-config-server"
  profiles:
    # active: native # use native only if the configs are in classpath or in file system
    active: git
  cloud:
    config:
      server:
        # native: # use native only if the configs are in classpath or in file system
          # search-locations: "classpath:/config" # telling config server to where to look for
        git:
          uri: "https://github.com/egedemirtas/bank-app-config.git"
          default-label: main # this is the default branch of bank-app-config-server
          timeout: 5
          # try to clone the config repo to the local system during startup,
          # otherwise cloning of config repo will be made when the first request to config repo
          # so, we try to load all the config beforehand,
          # all configs will be ready before any requests are made
          clone-on-start: true
          # override any local changes when restarting config server,
          # this will ensure config server reads the latest changes in the main branch
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  readiness-state:
    enabled: true
  liveness-state:
    enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "thisIsAStrongPassword"

server:
  port: 8071